// Code generated by wit-bindgen-go. DO NOT EDIT.

package add

// Exports represents the caller-defined exports from "math:adder/add".
var Exports struct {
	// AddRandom represents the caller-defined, exported function "add-random".
	//
	//	add-random: func(a: s32) -> s32
	AddRandom func(a int32) (result int32)
}
