// Code generated by wit-bindgen-go. DO NOT EDIT.

package add

// This file contains wasmimport and wasmexport declarations for "math:adder".

//go:wasmexport math:adder/add#add-random
//export math:adder/add#add-random
func wasmexport_AddRandom(a0 uint32) (result0 uint32) {
	a := (int32)((uint32)(a0))
	result := Exports.AddRandom(a)
	result0 = (uint32)(result)
	return
}
